name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # JOB 1 : Tests API
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Étape 1 : Build
      - name: Build with Maven
        run: mvn -q clean package

      # Étape 2 : Démarrage de l'app en arrière-plan
      - name: Start Application
        run: |
          # utilisation de *.jar pour éviter les erreurs de nommage (solution vs standard)
          nohup java -jar target/*.jar > app.log 2>&1 &

      # Étape 3 : Attente de disponibilité (Script du TP)
      - name: Wait for API to be ready
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:8080/health > /dev/null; then
              echo "API is up!"
              exit 0
            fi
            echo "Waiting API..."
            sleep 2
          done
          echo "API not ready"
          tail -n 200 app.log || true
          exit 1

      # Étape 5 : Exécution des tests Hurl (Script du TP)
      - name: Run API tests (Hurl via Docker)
        run: |
          docker run --rm \
            --add-host=host.docker.internal:host-gateway \
            -v ${{ github.workspace }}:/work \
            ghcr.io/orange-opensource/hurl:latest \
            --test /work/src/test/java/api/*.hurl

      # Pour le debug si ça plante
      - name: Show application logs on failure
        if: failure()
        run: cat app.log

  # JOB 2 : Sécurité (Ne se lance que si api-tests réussit)
  security-scan:
    needs: api-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Application
        run: mvn -q clean package

      - name: Start Application
        run: |
          nohup java -jar target/*.jar > app.log 2>&1 &

      - name: Wait for API
        run: |
          timeout 30s bash -c 'until curl -s http://localhost:8080/health; do sleep 2; done'

      # Scan OWASP ZAP (Baseline Scan)
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:8080'
          # On ignore les erreurs pour ce TP sinon la CI va passer rouge au moindre warning
          allow_issue_writing: false
          fail_action: false 
          cmd_options: '-a' # Include alpha rules